/*
 * Temperature Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.18
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Data struct {

	Id string `json:"id,omitempty"`

	Temperature float32 `json:"temperature,omitempty"`

	Timestamp int32 `json:"timestamp,omitempty"`
}
